Repository YU-RentCar/yurentcar-fe-web, pull requests merged in 2023-06, with the labels that each got.

#36 [Setting/#35] react router redux setting
  package-lock.json
  package.json
  src/index.js
  src/store.js
Labels: 📐 Setting

#38 [Feat/#37] 마이페이지 라우터 및 Nav 링크 설정
  src/App.js
  src/components/Nav.js
  src/pages/home/Home.js
Labels: ✨ Feat

#41 [Refactor/#39] 홈 UI 분리
  src/App.js
  src/assets/Map.svg
  src/components/Nav.js
  src/pages/home/Home.js
  src/pages/home/homeInquireCar/HomeInquireCar.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/HomeSearchPreferOption.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/internalComponents/CheckboxForm.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/internalComponents/SelectList.js
  src/pages/home/homeSelectLocation/HomeSelectLocation.js
  src/pages/home/homeSelectLocation/internalComponents/LocationList.js
  src/pages/home/homeSelectLocation/internalComponents/Map.js
Labels: 🔭 Refactor

#43 [Setting/#42] axios를 개발 환경에 추가
  package-lock.json
  package.json
Labels: 📐 Setting

#45 [Refactor/#40] 사용자 기본 정보 선호 차량 옵션 UI 수정 및 소셜 로그인 하이퍼링크 추가
  src/pages/auth/Auth.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPagePreferCar/internalComponents/DefaultItem.js
  src/pages/myPage/myPagePreferCar/internalComponents/ItemList.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
Labels: 🔭 Refactor

#46 [Feat/#44] 로그인 로직 구현
  src/App.js
  src/pages/auth/Auth.js
  src/store.js
Labels: ✨ Feat

#51 [Feat/#50] home 경로의 달력, 시간 선택하는 기능 추가
  package-lock.json
  package.json
  src/pages/home/homeSelectLocation/HomeSelectLocation.js
  src/pages/home/homeSelectLocation/internalComponents/TimeSelectForm.js
Labels: ✨ Feat

#53 [Feat/#47] 마이페이지 로직 구현
  src/App.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPageRecord/MyPageRecord.js
  src/pages/myPage/myPageRecord/internalComponents/Point.js
  src/pages/myPage/myPageRecord/internalComponents/Recent.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
  src/pages/myPage/myPageUserInfo/internalComponents/DefaultItem.js
  src/store.js
Labels: ✨ Feat

#54 [Refactor/#52] redux 를 통한 데이터 정리
  src/pages/home/homeInquireCar/homeSearchPreferOption/HomeSearchPreferOption.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/internalComponents/CheckboxForm.js
  src/pages/home/homeSelectLocation/HomeSelectLocation.js
  src/store.js
Labels: 🔭 Refactor

#56 [Fix/#49] 새로고침 라우터 fix
  src/App.js
Labels: 🔧 Fix

#58 [Feat/#55] 서버에서 선호 필터를 받아와 사용자에게 보여주는 기능 추가.
  src/pages/home/homeInquireCar/homeSearchPreferOption/HomeSearchPreferOption.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/internalComponents/CheckboxForm.js
Labels: ✨ Feat

#60 [Feat/#57] axios 모듈화 및 interceptor 구현
  src/api/MyPageAxios.js
  src/api/interceptors.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPageRecord/internalComponents/Point.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
Labels: ✨ Feat

#63 [Feat/#62] 서버로부터 지점 리스트를 받아오는 기능 추가
  src/api/HomeAxios.js
  src/pages/home/homeSelectLocation/internalComponents/Map.js
Labels: ✨ Feat

#69 [Feat/#67] 예약 상세 조회 페이지 UI 및 로직 전체 구현
  src/api/DetailAxios.js
  src/pages/myPage/MyPage.js
  src/pages/myPage/myPageDetail/MyPageDetail.js
  src/pages/myPage/myPageDetail/internalComponents/AccidentRecord.js
  src/pages/myPage/myPageDetail/internalComponents/CarInfo.js
  src/pages/myPage/myPageDetail/internalComponents/CarSpec.js
  src/pages/myPage/myPageDetail/internalComponents/Close.js
  src/pages/myPage/myPageDetail/internalComponents/Driver.js
  src/pages/myPage/myPageDetail/internalComponents/Insurance.js
  src/pages/myPage/myPageDetail/internalComponents/Open.js
  src/pages/myPage/myPageDetail/internalComponents/Point.js
  src/pages/myPage/myPageDetail/internalComponents/Price.js
  src/pages/myPage/myPageDetail/internalComponents/RepairRecord.js
  src/pages/myPage/myPageDetail/internalComponents/Resv.js
  src/pages/myPage/myPageResvCardView/MyPageResvCardView.js
Labels: ✨ Feat

#72 [Refactor/#70] 마이페이지 전체 로직 수정
  src/api/MyPageAxios.js
  src/pages/myPage/myPageAccount/myPageAccount.js
  src/pages/myPage/myPageDetail/internalComponents/CarSpec.js
  src/pages/myPage/myPageRecord/internalComponents/CarCard.js
  src/pages/myPage/myPageRecord/internalComponents/Recent.js
  src/pages/myPage/myPageResvCardView/MyPageResvCardView.js
  src/pages/myPage/popUp/PointRecord.js
  src/pages/myPage/popUp/ResvCard.js
  src/pages/myPage/popUp/ResvRecord.js
  src/pages/myPage/popUp/Review.js
Labels: 🔭 Refactor
