Repository YU-RentCar/yurentcar-fe-web, pull requests merged in 2023-05, with the labels that each got.

#3 [Setting/#1] 이슈 템플릿, 풀 리퀘스트 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📐 Setting

#4 [Docs/#2] 이슈 종류 이모지 변경
  README.md
Labels: 📄 Docs

#6 [PRMerge/#1, #2] 이슈 & 풀 리퀘스트 템플릿 적용 및 이슈 종류 이모지 변경 적용
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 📣 PRMerge

#8 [Docs/#7] README.md 에 PRMerge 에 관련된 내용 추가
  README.md
Labels: 📄 Docs

#10 [Setting/#9] 컴포넌트와 페이지 관리를 위해 src 하위에 폴더 추가
  src/components/.gitkeep
  src/pages/.gitkeep
Labels: 📐 Setting

#12 [PRMerge/#7, #9] README PRMerge 관련 내용 추가 및 기초 파일 구조 세팅 적용
  README.md
  src/components/.gitkeep
  src/pages/.gitkeep
Labels: 📣 PRMerge

#14 Feat/#13 web bgcolor nav design
  src/App.js
  src/assets/Logo.png
  src/components/Nav.js
Labels: ✨ Feat

#17 [Feat/#16] 마이페이지 관련 파일 구조 세팅 및 사용자의 현재 예약 정보 카드뷰 UI 구현
  src/assets/ExCar.png
  src/pages/myPage/MyPage.js
  src/pages/myPage/myPageResvCardView/MyPageResvCardView.js
Labels: ✨ Feat

#19 [Feat/#18] 마이페이지 사용자의 기본 정보 및 선호 차량 옵션 UI 구현
  src/pages/myPage/MyPage.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPagePreferCar/internalComponents/PreferOptions.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
  src/pages/myPage/myPageUserInfo/internalComponents/DefaultItem.js
Labels: ✨ Feat

#21 [Refactor/#20] 마이페이지 현재 예약 정보 카드뷰 UI 수정
  src/pages/myPage/myPageResvCardView/MyPageResvCardView.js
Labels: 🔭 Refactor

#23 [Feat/#22] 마이페이지 사용자 서비스 이용 내역, 면허 정보, 계정 관리 UI 구현
  src/pages/myPage/MyPage.js
  src/pages/myPage/myPageAccount/myPageAccount.js
  src/pages/myPage/myPageLicense/MyPageLicense.js
  src/pages/myPage/myPageLicense/internalComponents/Item.js
  src/pages/myPage/myPageRecord/MyPageRecord.js
  src/pages/myPage/myPageRecord/internalComponents/CarCard.js
  src/pages/myPage/myPageRecord/internalComponents/Point.js
  src/pages/myPage/myPageRecord/internalComponents/Recent.js
  src/pages/myPage/myPageRecord/internalComponents/Reservation.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
  src/pages/myPage/myPageUserInfo/internalComponents/DefaultItem.js
Labels: ✨ Feat

#24 [Feat/#15] 홈에서 시간과 지점을 정하는 컴포넌트 화면 구현
  src/assets/Map.svg
  src/assets/listShowIcon.png
  src/pages/home/homeSelectLocation/HomeSelectLocation.js
  src/pages/home/homeSelectLocation/internalComponents/LocationList.js
  src/pages/home/homeSelectLocation/internalComponents/Map.js
  src/pages/home/homeSelectLocation/internalComponents/TimeSelectForm.js
Labels: ✨ Feat

#27 [Refactor/#26] 마이페이지 컨텐츠 UI 세로 비율 조정
  src/pages/myPage/myPageAccount/myPageAccount.js
  src/pages/myPage/myPageLicense/MyPageLicense.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPageRecord/MyPageRecord.js
  src/pages/myPage/myPageRecord/internalComponents/Point.js
  src/pages/myPage/myPageRecord/internalComponents/Recent.js
  src/pages/myPage/myPageRecord/internalComponents/Reservation.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
Labels: 🔭 Refactor

#30 [Feat/#29] 홈 화면의 시간, 지점 검색 컴포넌트가 접혀있을 경우의 UI 구현
  src/pages/home/homeSelectLocation/HomeSelectLocation.js
Labels: ✨ Feat

#31 [Feat/#28] 마이페이지 팝업과 알림창 UI 구현 및 전체적인 주석, 로직 보완 및 추가 구현
  src/assets/Close.png
  src/pages/myPage/MyPage.js
  src/pages/myPage/myPageAccount/myPageAccount.js
  src/pages/myPage/myPageLicense/MyPageLicense.js
  src/pages/myPage/myPageLicense/internalComponents/Item.js
  src/pages/myPage/myPagePreferCar/MyPagePreferCar.js
  src/pages/myPage/myPagePreferCar/internalComponents/DefaultItem.js
  src/pages/myPage/myPagePreferCar/internalComponents/ItemList.js
  src/pages/myPage/myPagePreferCar/internalComponents/PreferOptions.js
  src/pages/myPage/myPageRecord/MyPageRecord.js
  src/pages/myPage/myPageRecord/internalComponents/CarCard.js
  src/pages/myPage/myPageRecord/internalComponents/Point.js
  src/pages/myPage/myPageRecord/internalComponents/Recent.js
  src/pages/myPage/myPageRecord/internalComponents/Reservation.js
  src/pages/myPage/myPageResvCardView/MyPageResvCardView.js
  src/pages/myPage/myPageUserInfo/MyPageUserInfo.js
  src/pages/myPage/myPageUserInfo/internalComponents/ChangeNickname.js
  src/pages/myPage/myPageUserInfo/internalComponents/DefaultItem.js
  src/pages/myPage/popUp/Alert.js
  src/pages/myPage/popUp/PointRecord.js
  src/pages/myPage/popUp/ResvCard.js
  src/pages/myPage/popUp/ResvRecord.js
  src/pages/myPage/popUp/Review.js
Labels: ✨ Feat

#33 [Feat/#25] 홈 화면 차량 조회 UI 구현
  src/pages/home/homeInquireCar/HomeInquireCar.js
  src/pages/home/homeInquireCar/homeNotice/HomeNotice.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/HomeSearchPreferOption.js
  src/pages/home/homeInquireCar/homeSearchPreferOption/internalComponents/SelectList.js
Labels: ✨ Feat

#34 [Feat/#32] 소셜 로그인 UI 구현
  src/assets/Kakao.png
  src/assets/Naver.png
  src/pages/auth/Auth.js
Labels: ✨ Feat
